apiVersion: apps/v1
kind: Deployment
metadata:
  name: rider app
  labels:
    app: rider app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rider app
  template:
    metadata:
      labels:
        app: rider app
    spec:
      containers:
        - name: rider app
          image: username/rider app:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
