apiVersion: apps/v1
kind: Deployment
metadata:
  name: rider_app
  labels:
    app: rider_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rider_app
  template:
    metadata:
      labels:
        app: rider_app
    spec:
      containers:
        - name: rider_app
          image: username/rider_app:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
